name: Deploy IIS via Ansible

on:
  push:
    branches:
      - main

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar VENV e Instalar Ansible + WinRM
        run: |
          python3 -m venv ansible_venv
          ansible_venv/bin/pip install --upgrade pip
          ansible_venv/bin/pip install ansible pywinrm requests

      - name: Criar Inventário Dinâmico com Secrets
        run: |
          mkdir -p ansible
          echo "[windows]" > ansible/inventory.ini
          echo "${{ secrets.AZURE_VM_IP }} ansible_user=${{ secrets.WIN_USER }} ansible_password='${{ secrets.WIN_PASSWORD }}' ansible_port=5985 ansible_connection=winrm ansible_winrm_transport=ntlm ansible_winrm_server_cert_validation=ignore" >> ansible/inventory.ini

      - name: Executar Playbook
        run: |
          ansible_venv/bin/ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
